name: backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Setup mongodb
      run: sudo docker run -d -p 27017:27017 mongo:latest

    - name: Test
      run: go test -v ./tests
      working-directory: ./backend
